title: Warl-G's Blog
author: Warl-G
email: guoru123@sina.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
function:
  baidu_analysis: 58ab546711cec90b5b0a6bc75b580abe
  gitalk_id: f880a4741a00031570d7
  gitalk_secret: a2e47c5863efa96322515ba45f85b78f65c9f5a0
  gitalk_repo: Warl-G.github.io

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Warl-G's Blog
  tagline: 充能中...
  date_format: "%F" #"%b %-d, %Y"
  style: black
  showNav: true
  showPicker: true

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  Warl-G/Warl-G.github.io
    #linkedIn: in/thelehhman
    #rss: rss
    jianshu: 63319e52f015
    #zhihu:   Warl-G
    #sspai:  l1d4a3pm
    #juejin: 5df4bb5b518825121b436d5e
    #csdn:

 
markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge  

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME

 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed